// utils/sampleData.js
export const orders = [
  {
    id: "#RB5625",
    date: "29 April 2024",
    product: "product-1(1)",
    customerName: "Anna M. Hines",
    email: "anna.hines@mail.com",
    phone: "(+1)-555-1564-261",
    address: "Burr Ridge/Illinois",
    paymentType: "Credit Card",
    status: "Completed",
  },
  {
    id: "#RB9652",
    date: "25 April 2024",
    product: "product-4",
    customerName: "Judith H. Fritsche",
    email: "judith.fritsche@mail.com",
    phone: "(+57)-305-5579-759",
    address: "SULLIVAN/Kentucky",
    paymentType: "Credit Card",
    status: "Completed",
  },
  {
    id: "#RB5984",
    date: "25 April 2024",
    product: "product-5",
    customerName: "Peter T. Smith",
    email: "peter.smith@mail.com",
    phone: "(+33)-655-5187-93",
    address: "Yreka/California",
    paymentType: "Pay Pal",
    status: "Completed",
  },
  {
    id: "#RB3625",
    date: "21 April 2024",
    product: "product-6",
    customerName: "Emmanuel J. Delcid",
    email: "emmanuel.delcid@mail.com",
    phone: "(+30)-693-5553-637",
    address: "Atlanta/Georgia",
    paymentType: "Pay Pal",
    status: "Pending",
  },
  {
    id: "#RB5987",
    date: "25 April 2024",
    product: "product-5",
    customerName: "Peter T. Smith",
    email: "peter.smith@mail.com",
    phone: "(+33)-655-5187-93",
    address: "Yreka/California",
    paymentType: "Pay Pal",
    status: "Completed",
  },
  {
    id: "#RB3925",
    date: "21 April 2024",
    product: "product-6",
    customerName: "Emmanuel J. Delcid",
    email: "emmanuel.delcid@mail.com",
    phone: "(+30)-693-5553-637",
    address: "Atlanta/Georgia",
    paymentType: "Pay Pal",
    status: "Pending",
  },
  {
    id: "#RB5997",
    date: "25 April 2024",
    product: "product-5",
    customerName: "Peter T. Smith",
    email: "peter.smith@mail.com",
    phone: "(+33)-655-5187-93",
    address: "Yreka/California",
    paymentType: "Pay Pal",
    status: "Completed",
  },
  {
    id: "#RB4925",
    date: "21 April 2024",
    product: "product-6",
    customerName: "Emmanuel J. Delcid",
    email: "emmanuel.delcid@mail.com",
    phone: "(+30)-693-5553-637",
    address: "Atlanta/Georgia",
    paymentType: "Pay Pal",
    status: "Pending",
  },
  // Add additional rows if needed for pagination testing
];
