export const ProductData = [
  {
    id: 1,
    product_name: "Classic Denim Sneakers Limited Collectable Items",
    product_description:
      "Soft and breathable cotton T-shirt for everyday wear.",
    product_brand: "BrandA",
    category: "Men",
    sub_category: "Footwear",
    variants: [
      {
        id: 1,
        pid: 101,
        color: "Blue",
        images: [
          "/Product-details-list/p8.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["UK6", "UK7", "UK8"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 102,
        color: "Black",
        images: [
          "/Product-details-list/p1.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["UK7", "UK8", "UK9", "UK10"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 103,
        color: "White",
        images: [
          "/Product-details-list/p6.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["UK6", "UK8", "UK9"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 2,
    product_name: "Slim Fit Jeans",
    product_description: "Slim-fit jeans with stretch fabric for comfort.",
    product_brand: "BrandB",
    category: "Men",
    sub_category: "Trouser",
    variants: [
      {
        id: 1,
        pid: 201,
        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["XS", "S", "M", "L", "XL"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 202,
        color: "Black",
        images: [
          "/Product-details-list/p7.avif",
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["XS", "S", "M", "L", "XL"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 203,
        color: "Red",
        images: [
          "/Product-details-list/p4.avif",
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["M", "L", "XL"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 3,
    product_name: "Casual Sneakers",
    product_description: "Lightweight sneakers perfect for casual outings.",
    product_brand: "BrandC",
    product_color: ["White"],
    category: "Women",
    sub_category: "Footwares",
    variants: [
      {
        id: 1,
        pid: 301,
        color: "Blue",
        images: [
          "/Product-details-list/p6.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["UK6", "UK7", "UK8"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 302,
        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["UK7", "UK8", "UK9", "UK10"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 303,
        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["UK6", "UK8", "UK9"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 4,

    product_name: "Graphic Print T-shirt",
    product_description:
      "Stylish graphic T-shirt made from high-quality cotton.",
    product_brand: "BrandD",
    product_color: ["Red"],
    category: "Kids",
    sub_category: "T-shirts",
    variants: [
      {
        id: 1,
        pid: 401,
        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["UK6", "UK7", "UK8"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 402,
        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["UK7", "UK8", "UK9", "UK10"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 403,
        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["UK6", "UK8", "UK9"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 5,

    product_name: "Formal Shirt",
    product_description: "Long-sleeved formal shirt, perfect for office wear.",
    product_brand: "BrandE",
    product_color: ["White"],
    category: "Men",
    sub_category: "Shirts",
    variants: [
      {
        id: 1,
        pid: 501,
        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["XS", "S", "M", "L", "XL"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 502,
        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["XS", "S", "M"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 503,
        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["L", "XL"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 6,
    product_name: "Running Shoes",
    product_description:
      "High-performance running shoes with excellent cushioning.",
    product_brand: "BrandF",
    product_color: ["Black"],
    category: "Men",
    sub_category: "Footwares",
    variants: [
      {
        id: 1,
        pid: 601,
        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["UK6", "UK7", "UK8"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 602,
        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["UK7", "UK8", "UK9", "UK10"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 603,
        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["UK6", "UK8", "UK9"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 7,
    product_name: "Denim Jacket",
    product_description: "Classic denim jacket with a vintage feel.",
    product_brand: "BrandG",
    product_color: ["Blue"],
    category: "Women",
    sub_category: "Shirts",
    variants: [
      {
        id: 1,
        pid: 701,
        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["UK6", "UK7", "UK8"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 702,
        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["UK7", "UK8", "UK9", "UK10"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 703,
        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["UK6", "UK8", "UK9"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 8,
    product_name: "Polo T-shirt",
    product_description: "Comfortable polo T-shirt, ideal for a casual look.",
    product_brand: "BrandH",
    product_color: ["Green"],
    category: "Men",
    sub_category: "T-shirts",
    variants: [
      {
        id: 1,
        pid: 801,
        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["XS", "S", "M", "L"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 802,
        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["XS", "S", "M"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 803,
        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["XS", "S", "M"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 9,
    product_name: "Cargo Pants",
    product_description: "Utility-style cargo pants with multiple pockets.",
    product_brand: "BrandI",
    product_color: ["Khaki"],
    category: "Men",
    sub_category: "Trouser",
    variants: [
      {
        id: 1,
        pid: 901,
        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["M", "L", "XL"],
        price: 170.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 902,
        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["XS", "S", "M", "L"],
        price: 240.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 903,
        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["S", "M", "L", "XL"],
        price: 250.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    id: 10,
    product_name: "Slip-on Sandals",
    product_description: "Easy-to-wear slip-on sandals, perfect for the beach.",
    product_brand: "BrandJ",
    product_color: ["Yellow"],
    category: "Women",
    sub_category: "Footwares",
    variants: [
      {
        id: 1,
        pid: 1001,
        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["UK6", "UK7", "UK8"],
        price: 222.99,
        sale_price: 26.99,
      },
      {
        id: 2,
        pid: 1002,
        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["UK7", "UK8", "UK9", "UK10"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        id: 3,
        pid: 1003,
        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["UK6", "UK8", "UK9"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
];
