export const ProductData = [
  {
    product_id: 1,
    product_name: "Classic Denim Sneakers Limited Collectable Items",
    product_description:
      "Soft and breathable cotton T-shirt for everyday wear.",
    product_brand: "BrandA",
    category: "Men",
    sub_category: "Footwear",
    variants: [
      {
        variant_id: 1,
        product_id: 1,

        color: "Blue",
        images: [
          "/Product-details-list/p8.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["UK6", "UK7", "UK8"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        variant_id: 2,
        product_id: 1,

        color: "Black",
        images: [
          "/Product-details-list/p1.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["UK7", "UK8", "UK9", "UK10"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        variant_id: 3,
        product_id: 1,

        color: "White",
        images: [
          "/Product-details-list/p6.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["UK6", "UK8", "UK9"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    product_id: 2,
    product_name: "Slim Fit Jeans",
    product_description: "Slim-fit jeans with stretch fabric for comfort.",
    product_brand: "BrandB",
    category: "Men",
    sub_category: "Trouser",
    variants: [
      {
        variant_id: 1,
        product_id: 2,

        color: "Blue",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["XS", "S", "M", "L", "XL"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        variant_id: 2,
        product_id: 2,

        color: "Black",
        images: [
          "/Product-details-list/p7.avif",
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["XS", "S", "M", "L", "XL"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        variant_id: 3,
        product_id: 2,

        color: "Red",
        images: [
          "/Product-details-list/p4.avif",
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["M", "L", "XL"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  {
    product_id: 3,
    product_name: "Casual Sneakers",
    product_description: "Lightweight sneakers perfect for casual outings.",
    product_brand: "BrandC",
    category: "Women",
    sub_category: "Footwear",
    variants: [
      {
        variant_id: 1,
        product_id: 3,

        color: "Blue",
        images: [
          "/Product-details-list/p6.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 50,
        sizes: ["UK6", "UK7", "UK8"],
        price: 22.99,
        sale_price: 26.99,
      },
      {
        variant_id: 2,
        product_id: 3,

        color: "Black",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 70,
        sizes: ["UK7", "UK8", "UK9", "UK10"],
        price: 24.99,
        sale_price: 27.99,
      },
      {
        variant_id: 3,
        product_id: 3,

        color: "Red",
        images: [
          "/Product-details-list/p3.avif",
          "/Product-details-list/p1.avif",
          "/Product-details-list/p7.avif",
          "/Product-details-list/p4.avif",
          "/Product-details-list/p6.avif",
          "/Product-details-list/p8.avif",
          "/Product-details-list/p5.avif",
          "/Product-details-list/p2.avif",
        ],
        stock: 30,
        sizes: ["UK6", "UK8", "UK9"],
        price: 25.99,
        sale_price: 28.99,
      },
    ],
  },
  // ...continue with corrected objects for remaining products...
];
